name: Cleanup old branches
on:
  push:
    branches:
      - master
      - develop
jobs:
  cleanup:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.1
        with:
          repo_token: ${{ github.token }}
          date: '15 days ago'
          dry_run: true
